# Fast Fetch Demo Configuration
# Quick planning demo with Fetch robot in empty space

planning:
  robot:
    name: "fetch"
    
  environment:
    name: "empty"
    description: "Fast planning in empty space"
    
  planner:
    name: "PRM"
    planning_time: 0.5
    simplification_time: 0.2
    optimize_path: false
    
  output:
    write_path: true
    description: "Fast Fetch Planning Demo with PRM"

visualization:
  enabled: true
  auto_start: true
  
  animation:
    duration: 5.0
    loop: false
    draw_trajectory: true
    
  display:
    gui: true
    interactive_mode: false
    verbose: false 