# Panda Demo Configuration
# This configuration demonstrates Panda robot planning in sphere cage with visualization

planning:
  robot:
    name: "panda"
    
  environment:
    name: "sphere_cage"
    description: "Navigate through a cage of spheres"
    
  planner:
    name: "BIT*"
    planning_time: 2.0
    simplification_time: 1.0
    optimize_path: true
    
  output:
    write_path: true
    description: "Panda Sphere Cage Demo with BIT* Planner"

visualization:
  enabled: true
  auto_start: false
  
  animation:
    duration: 5.0
    loop: true
    draw_trajectory: true
    
  display:
    gui: true
    interactive_mode: false
    verbose: false 