# VAMP-OMPL Simple Custom Obstacles Demo
# This is a simplified example with just sphere obstacles

planning:
  robot:
    name: "panda"
    
  environment:
    name: "custom"
    description: "Simple environment with sphere obstacles"
    
    custom:
      obstacles:
        obstacle_1:
          type: "sphere"
          name: "obstacle_1"
          position_x: 0.2
          position_y: 0.2
          position_z: 0.5
          radius: 0.1
          
        obstacle_2:
          type: "sphere"
          name: "obstacle_2"
          position_x: -0.2
          position_y: -0.2
          position_z: 0.7
          radius: 0.08
          
        obstacle_3:
          type: "sphere"
          name: "obstacle_3"
          position_x: 0.0
          position_y: -0.3
          position_z: 0.4
          radius: 0.09
          
  planner:
    name: "RRT-Connect"
    planning_time: 2.0
    simplification_time: 0.5
    optimize_path: false
    
  output:
    write_path: true
    description: "Simple Spheres Demo"

visualization:
  enabled: true
  auto_start: true
  
  animation:
    duration: 5.0
    loop: false
    draw_trajectory: true
    
  display:
    gui: true
    verbose: false 