# UR5 Table Manipulation Demo
# This configuration shows UR5 robot planning around table obstacles

planning:
  robot:
    name: "ur5"
    
  environment:
    name: "table"
    description: "Navigate around table obstacles"
    
  planner:
    name: "RRT-Connect"
    planning_time: 3.0
    simplification_time: 1.5
    optimize_path: false
    
  output:
    write_path: true
    description: "UR5 Table Manipulation with RRT-Connect"

visualization:
  enabled: true
  auto_start: true
  
  animation:
    duration: 5.0
    loop: false
    draw_trajectory: true
    
  display:
    gui: true
    interactive_mode: false
    verbose: false 