# VAMP-OMPL Configuration File
# This file contains all configuration options for both planning and visualization

# ==============================================================================
# PLANNING CONFIGURATION
# ==============================================================================
planning:
  # Robot configuration
  robot:
    name: "panda"                    # Options: "panda", "ur5", "fetch"
    urdf_path: ""                    # Custom URDF path (optional, leave empty for default)
    
  # Environment configuration  
  environment:
    name: "sphere_cage"              # Options: "empty", "sphere_cage", "table"
    description: "Sphere cage environment for demonstration"
    
  # Planner configuration
  planner:
    name: "BIT*"                     # Options: "BIT*", "RRT-Connect", "PRM"
    planning_time: 1.0               # Maximum planning time in seconds
    simplification_time: 0.5         # Time for path simplification in seconds
    optimize_path: false             # Whether to optimize for path cost
    
  # Output configuration
  output:
    write_path: true                 # Whether to write solution path to file
    description: "VAMP-OMPL Demo from YAML Config"

# ==============================================================================
# VISUALIZATION CONFIGURATION
# ==============================================================================
visualization:
  # Basic settings
  enabled: true                      # Whether to run visualization after planning
  auto_start: true                   # Whether to start animation automatically (false = wait for user input)
  
  # Animation settings
  animation:
    duration: 5.0                   # Animation duration in seconds
    loop: false                      # Whether to loop animation continuously
    draw_trajectory: true            # Whether to draw trajectory lines
    
  # Display settings
  display:
    gui: true                        # Whether to show PyBullet GUI (false = headless)
    interactive_mode: false          # Whether to use interactive file selector
    verbose: false                   # Whether to show PyBullet debug output
    
  # Robot visualization settings (optional overrides)
  robot:
    name: ""                         # Override robot name (leave empty to use planning.robot.name)
    urdf_path: ""                    # Override URDF path (leave empty to use planning.robot.urdf_path)
    
  # Environment visualization settings (optional overrides)
  environment:
    name: ""                         # Override environment name (leave empty to use planning.environment.name)

# ==============================================================================
# PREDEFINED CONFIGURATIONS (Examples)
# ==============================================================================
# Uncomment and modify any of these predefined configs as needed:

# # Configuration 1: Panda + Sphere Cage + BIT*
# planning:
#   robot:
#     name: "panda"
#   environment:
#     name: "sphere_cage"
#   planner:
#     name: "BIT*"
#     planning_time: 1.0
#     simplification_time: 0.5
#   output:
#     write_path: true
# visualization:
#   enabled: true
#   animation:
#     duration: 15.0
#     loop: true

# # Configuration 2: UR5 + Table Scene + RRT-Connect
# planning:
#   robot:
#     name: "ur5"
#   environment:
#     name: "table"
#   planner:
#     name: "RRT-Connect"
#     planning_time: 2.0
#     simplification_time: 1.0
#   output:
#     write_path: true
# visualization:
#   enabled: true
#   animation:
#     duration: 12.0
#     draw_trajectory: true

# # Configuration 3: Fetch + Empty + PRM  
# planning:
#   robot:
#     name: "fetch"
#   environment:
#     name: "empty"
#   planner:
#     name: "PRM"
#     planning_time: 1.5
#     simplification_time: 0.5
#   output:
#     write_path: true
# visualization:
#   enabled: true
#   animation:
#     duration: 8.0
#     loop: false 