# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0  # Adjust version as needed
    hooks:
      - id: clang-format
        args: [-style=Google]  # Change to LLVM, Mozilla, etc., if needed
